### ISSUE TITLE
Mutation within onSet handler generates a warning

### ISSUE THREAD

**Issue by eizenberg** [inferinc/bobtail#11]
Hey,
I'm resetting a timer value every time some text is modified.

``` coffeescript
text = rx.cell 'hello'
timer = rx.cell 0
setInterval (timer.set timer.get() + 1), 1000
text.onSet.sub (o,n) -> (timer.set 0) if o != n
```

This generates the "Mutation to observable detected during a bind context" warning. 
I understand why the warning was generated, but I'm not sure how else I should approach the use-case.

**Comment by yang** [comment]
One tangential thing to note is that you probably meant to make that line a closure:

``` coffeescript
setInterval (-> timer.set timer.get() + 1), 1000
```

For your actual question: there are a few new utilities and primitives due out in this next release (already started documenting some on the website; you can find highlights under [Changes](http://yang.github.io/reactive-coffee/changes.html)). The most appropriate one for this case is:

``` coffeescript
text.onSet.sub rx.skipFirst -> timer.set 0
```

(You actually no longer need `if o != n` because cells are now lazy and no longer propagate events if their value doesn't change, which has been a low-hanging performance change.)

The callback is thus no longer called from within a `bind`, which would have potentially led to dependency cycles and thus stack overflows (e.g. if you were to bind something to or call `timer.get()`).

Will update this thread once this is pushed to master.

**Comment by eizenberg** [comment]
That's great. Thanks.
