### ISSUE TITLE
ObsArray should support sort?

### ISSUE THREAD

**Issue by allain** [inferinc/bobtail#18]

**Comment by yang** [comment]
Hi @allain—you can (as of a few commits before this post) perform arbitrary array operations with `rx.cellToArray`.  This takes a cell containing any arbitrary array value (named `xs` in the following example) and maintains an `ObsArray` reflecting its contents (automatically computing differences and propagating changes):

``` coffeescript
xs = rx.cell(['b','c','a'])
$('body').append(
  ul rx.cellToArray(xs).map (x) ->
    li "Value: #{x}"
)
xs.set(_.sortBy(xs.get(), _.identity))
```

This will also be in the next release, due within the coming week or so.

Note though that for the time being, since change propagations in `ObsArray.onChange` are represented as simple splices that cannot express reorderings, operations like `sort` may cause an entire dependent `MappedDepArray` downstream to be re-generated (re-computing the mapped function) rather than simply reordered. With a new more expressive change propagation event type (planned), changes will be able to express reorderings.

**Comment by yang** [comment]
Forgot to close this—both `cellToArray` and `SrcArray.update` are in the latest release.
