### ISSUE TITLE
Make jQuery optional

### ISSUE THREAD

**Issue by paulmillr** [inferinc/bobtail#19]
hey -- would be really nice if this was optional

we want to use pure dom in our project, it's much faster and stuff

what do you think?

**Comment by yang** [comment]
@paulmillr We're not married to jQuery (i.e. we would definitely give relevant pull requests consideration), but it's not a super high priority, because:
- jQuery is familiar, vetted, and provides cross-browser platform portability, esp. around things like events - reconciling browser quirks is not a problem we want to reinvent solutions for
- some benchmarks suggest it's not much of a win for the use cases here: jQuery isn't being used for its selector language, and is instead used for cross-browser low-level DOM manipulation, where actual browser DOM time is what dominates

**Comment by yang** [comment]
Closing for now as duplicate of #3.
