### ISSUE TITLE
Functional Programming Basics

### ISSUE THREAD

**Issue by deanrad** [inferinc/bobtail#27]
Could you leave some resources on FRP - for example this paper http://docs.racket-lang.org/frtime/ uses the terms cell, bind, and lift which I've seen in your library, but could you list your sources of inspiration, and did you borrow the algo of recording and stuff or write it yourself ? Just looking to add to the background on this project if possible ! :)

**Comment by yang** [comment]
Definitely! The main source of inspiration was actually JavaFX, which is where `bind` comes from. I don't know about `cell`, I guess it's just a natural name that occurred (probably a subconscious nod to spreadsheets, which are the most prevalent form of reactive programming).

Though the terms are fuzzy to start with, I'm not sure reactive.coffee is as much about FRP as it is about RP in general—in particular, things like cells are all about mutable state, very non-functional. So I'm also confused about FrTime. When I think FRP, I usually think of combinators over streams, closer to libraries in http://www.haskell.org/haskellwiki/Functional_Reactive_Programming. reactive.coffee is a discrete reactive programming system, and doesn't emphasize continuous abstractions like integration and differentiation (which make more sense to me in e.g. game development). To be honest I have much more limited exposure to FRP than declarative client-side web development, so take this part with a heap of salt.

The recording algo is actually probably the most straightforward part (just program whatever is needed to Make It Work and clean up resources after itself...not really much of an interesting algo)—the hard part I usually find to be _design_, and striking the tricky balance between expressivity and simplicity. OK, we have cells...but what if we want to insert something into an array? So we have reactive arrays as well, with their own mutator methods. How do we represent/propagate changes to dependent arrays? Currently we propagate splices, but splicing can't express more complex operations like reorderings (sortings). What about mapping with indexes—what happens when you insert/shift elements? OK, indexes are maintained as cells. What other data structures besides arrays exist? Most importantly, driving all these questions—**is this the Right Way to program UIs**? Can we express elegantly all the complex UIs and widgets and dynamic behaviors we want within this framework? (And efficiently—i.e. not reconstructing the whole DOM on every operation?) It's a friggin' hard problem, but the nice thing about reactive.coffee is that it's small/simple enough that it's a relatively cheap stab that has so far worked out nicely enough for my team and me that it made sense to publish/share it.

**Comment by deanrad** [comment]
Thanks for the notes !
