### ISSUE TITLE
Reactive-Coffee vs Reactive.js

### ISSUE THREAD

**Issue by deanrad** [inferinc/bobtail#39]
Yang, I found this other reactive library which is a bit shorter in its implementation than reactive-coffee (even without rxt.tags), but I suspect not equal in feature parity. I can't quite figure out everything you accomplish in reactive-coffee though so I may need your help to understand what it accomplishes 

Could you help me understand the different aims between reactive-coffee and this one ? 
https://github.com/mattbaker/Reactive.js/blob/master/src/reactive.js

PS It appears my talk will not be accepted to RailsConf, but I'm still active in a couple of Javascript meetups in Chicago so am still interested in presenting/blogging on reactive-coffee including comparisons to others

**Comment by yang** [comment]
Hey, yep I've come across it and it is indeed very simple.  Major high-level differences:
- no automatic subscription management; you manually wire up cells together rather than declaratively define the cells in terms of each other
- no reactive arrays or other data structures, no support for fine-grained incremental changes
- no reactive view library (as you noted)

It's very simple and doesn't try to do a whole lot.

BTW thanks for getting the word out on reactive.coffee!

**Comment by deanrad** [comment]
You're welcome - it hits a sweet spot for me, but the team at work will either want convincing or need comparisons to the things they know to make a good decision. Any other comparisons you want to make (like to Facebook React), feel free to add them !

**Comment by yang** [comment]
Sure, let me know if you guys have any specific questions beyond the differences highlighted in the related works page. I would love for something like reactive coffee to have already existed so that I wouldn't have to write or maintain it, but currently other libraries like react just don't solve the same need for me.
