### ISSUE TITLE
ReferenceError: div is not defined

### ISSUE THREAD

**Issue by softwarerero** [inferinc/bobtail#48]
Hi, I try to try rc. 

``` coffeescript
bind = rx.bind
#rxt.importTags()

$('#container').append(
  div {class: 'test'}
)
```

I do not understand from the documentation what rxt.importTags() is good for. I suspected it might be for importing the template DSL, but when I uncomment that line i get another error: `ReferenceError: rxt is not defined`.

Here are my scripts:

``` coffescript
    script(src="/reload/reload.js")
    script(src="/scripts/jquery-2.1.1.min.js")
    script(src="/scripts/underscore-1.6.0.js")
    script(src="/scripts/reactive-coffee-1.2.3.js")
```

Is this a bug or have I missed somthing (more likely)?

**Comment by yang** [comment]
Thanks for pointing out the documentation bug.  This is due to a recent change, part of the re-packaging for node, where `rxt` was moved to be a sub-namespace of the `rx` top-level namespace rather than its own top-level namespace.  This was to make consumption of the library simpler in module systems like node's.

I'll update the docs, but in the meantime `rx.rxt.importTags()` should work.

**Comment by softwarerero** [comment]
cool, thanks
