### ISSUE TITLE
Dist files do not appear to be ignored

### ISSUE THREAD

**Issue by drernie** [inferinc/bobtail#59]
When pulling from the upstream, I got a complaint about dist files not being in sync:

> CONFLICT (modify/delete): dist/reactive.js.map deleted in HEAD and modified in upstream/master. Version upstream/master of dist/reactive.js.map left in tree.
> CONFLICT (modify/delete): dist/reactive-coffee.min.js.map deleted in HEAD and modified in upstream/master. Version upstream/master of dist/reactive-coffee.min.js.map left in tree.
> CONFLICT (modify/delete): dist/reactive-coffee.min.js deleted in HEAD and modified in upstream/master. Version upstream/master of dist/reactive-coffee.min.js left in tree.
> CONFLICT (modify/delete): dist/reactive-coffee.js deleted in HEAD and modified in upstream/master. Version upstream/master of dist/reactive-coffee.js left in tree.
> Automatic merge failed; fix conflicts and then commit the result

The 'dist' directory is in .gitignore, but the files seem to be added anyway. Can you remove them?

**Comment by yang** [comment]
Aye, this is actually something I find annoying about how bower (and
component and other client-side git-based package managers) work—they
require you to have build artifacts in your git repository.  This
inevitably means whenever you rebase, you inevitably deal with conflicts.
Fortunately it's pretty easy to just resolve by re-generating the files
(since they're just build artifacts).
