### ISSUE TITLE
Allow binding functions inside array of contents

### ISSUE THREAD

**Issue by mateusmaso** [inferinc/bobtail#8]
I found some use cases that I need to append functions wrapped inside the contents array. Here is one example:

``` coffeescript
ul {}, [
   li {}, "Header"
   headerItems.map (item) -> li {}, bind -> item.name
   li {}, "Footer"
   footerItems.map (item) -> li {}, bind -> item.name
]
```

This code does not work and I saw that facebook react.js allow this kind of declarative code.
By the way, great lib!

**Comment by yang** [comment]
Thanks!  Here is a simple utility function we use for this, in order to keep the core clean/extensible:

``` coffeescript
ul {}, flatten [
  li {}, 'Header'
  headerItems.map (item) -> li {}, bind -> item.name
  li {}, 'Footer'
  headerItems.map (item) -> li {}, bind -> item.name
]
```

I'll add this utility in and document it.  The only caveat is that it does not have the full efficiency of a direct `map`, which will be more complicated to generalize (but `concat` will be on the combinator roadmap).  Also, we'll be adding array diff-ing (relatively high priority), which re-evaluates only dirty elements—that will get you 90%+ of the efficiency here.
